### DISCUSSION TITLE
Gitlab support -- running validation step in gitlab

### DISCUSSION THREAD

**Discussion by garethjudson** [flipt-io/flipt#2337] [Q&A]
Wasn't sure where to post but this is what I did to make the validation work in gitlab.
I created a custom container which I installed flipt into, basically, I had some issues with the default container. I'm not sure what was going wrong tbh, but it might be me doing something wrong, or some combination of gitlab and docker magic that I did wrong. But you probably don't need to do that. 

The project structure has the feature toggle yml stored in a directory 'toggles' at the root. I put a file per namespace 
I created a validation script, which looks like this:
```
#!/usr/bin/env bash
set -eu

flipt validate $(find toggles -type 'f' -name '*.features.yml')
```

And the .gitlab.yml step looks like:

```
build:
  image: <custom-flipt-docker-image-here>
  stage: build
  script:
    - scripts/validate.sh
  artifacts:
    when: always
    paths:
      - toggles/
```

I had to use find for the validate command, as glob expansion did not work as I expected, and flipt itself doesn't do the expansion.

I figured out that the '**/*.yml' was not matching multi-level subdirectories in sh or in bash. I verified by echoing the **/*.yml 
However I use zsh as my default shell and in that, it does match multi-levels rather than one. So I got different behaviour locally vs in the container.
 
This is was not the behaviour I expected-- so after playing around I found that using find was much easier. 
Hope this is useful for others.
