### DISCUSSION TITLE
Is it possible to implement multiple values for a single property in .features.yaml?

### DISCUSSION THREAD

**Discussion by shivomPatel** [flipt-io/flipt#2751] [Q&A] [answered]
Currently using v1.27.1.

I am using a Git backend and I have created a flag with a segment `dev-group` where the constraints are that a group has a `group-type` property of value `new` and an `env`  property of either `dev` or `qual`. I have provided a sample `.features.yml` file of what I would like to be able to do -- the second constraint of the `dev-group` segment.

I have looked through the docs but I have not been able to find anything that supports this type of feature that allows checking if a property value is one of a list of provided values. Could someone explain if this is possible, and if so, how to configure the constraint to do it?

I saw that [Discussion 584](https://github.com/flipt-io/flipt/discussions/584) asks a similar question but it doesn't seem to discuss the resolution method or if this feature is possible.

```yaml
namespace: lz-nola-prod
flags:
  - key: my-flag
    name: my-flag
    enabled: true
    variants:
      - key: enabled
        name: Enabled
      - key: disabled
        name: Disabled
    rules:
      - segment: dev-group
        distributions:
          - variant: enabled
            rollout: 100

segments:
  - key: dev-group
    name: dev-group segment
    constraints:
      - type: STRING_COMPARISON_TYPE
        property: group-type
        operator: eq
        value: new
      - type: STRING_COMPARISON_TYPE
        property: env
        operator: isoneof
        value: ["dev", "qual"]
    match_type: ALL_MATCH_TYPE

```

**Comment by markphelps** [comment, marked as answer]
Hey @shivomPatel ! thanks for the question. we definitely need to do a better job of documenting constraint types/operators. Will create a documentation issue for that

To answer your question, yes it is possible! 

Here's what the section of the YAML would look like:

```yaml
segments:
- key: dev-group
  name: dev-group
  constraints:
  - type: STRING_COMPARISON_TYPE
    property: env
    operator: isoneof
    value: '["dev","qual"]'
  match_type: ALL_MATCH_TYPE
```

So basically your example was correct, you might just need to enclose the JSON array in `' '`.

Here's what the accompanying config would look like in the UI:

![CleanShot 2024-02-06 at 09 18 04](https://github.com/flipt-io/flipt/assets/209477/d4d192e1-6502-426d-94f6-a52337bf5310)


One thing we could also add that we have talked about before is a `copy as YAML` or `export to YAML` button in the UI that would allow you to see what you configure in the UI would look like as YAML.
