### ISSUE TITLE
Configuration with postgress not working

### ISSUE THREAD

**Issue by ognif** [flipt-io/flipt#1035]
I try to install Flipt with your helm charts. I put everything from your config site to the config.yaml.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flipt.fullname" . }}
  labels:
    {{- include "flipt.labels" . | nindent 4 }}
data:
  config.yml: |
    cors:
      enabled: true

    log:
      level: ALL

    server:
      protocol: http
      host: 0.0.0.0
      http_port: 8080
      grpc_port: 18029

    meta:
      telemetry_enabled: false
      check_for_updates: false

    cache:
      memory:
        enabled: false

    db:
      url: 
      host: xxx.postgres.database.azure.com
      protocol: postgres
      name: flipt
      port: 5432
      user: xxx
      password: xxx
```
Flipt will not connect to the postgress database. Also inside the POD log there is not one line about the database used or connections issues or whatever. It looks like the settings get ignored.

If I start a flipt container on Azure and set Environmebt variables:

```
        environmentVariables:
          - name: FLIPT_DB_HOST
            value: xxx.postgres.database.azure.com
          - name: FLIPT_DB_PROTOCOL
            value: postgres
          - name: FLIPT_DB_NAME
            value: flipt
          - name: FLIPT_DB_PORT
            value: 5432
          - name: FLIPT_DB_USER
            value: xxx
          - name: FLIPT_DB_PASSWORD
            value: xxx
          - name: FLIPT_SERVER_GRPC_PORT
            value: 18029  
```
It works like a charme. 
What is the trick with an helm installation and config map?

### Version Info

Run `flipt --version` and paste the output here:

### Expected Behavior
I expect that flipt use the config map that is installed and do not ignore it.
I expect further, that a software will log anything about database 

Examples:

- OS: Linux
- Config file: See above
- Database used Postgress

**Comment by markphelps** [comment]
@ognif try removing `url` from the config .yaml

```yaml
db:
      url: <--- remove this
      host: xxx.postgres.database.azure.com
      protocol: postgres
      name: flipt
      port: 5432
      user: xxx
      password: xxx
```

It should look like this:

```yaml
      host: xxx.postgres.database.azure.com
      protocol: postgres
      name: flipt
      port: 5432
      user: xxx
      password: xxx
```

`url` takes precedence over `host` and `port` for the DB config: https://flipt.io/docs/configuration#database

Also `ALL` is not a valid log level, the valid log levels are `trace, debug, info, warn, error, fatal, panic`

Try setting the log level to `debug`
