### ISSUE TITLE
[FLI-197] OTel: Exporter config

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#1310]
We should likely model the configuration of the telemetry exporter to follow the same pattern as we do for cache:

```
telemetry:
  enabled: true
  exporter: jaeger
  jaeger:
    x:
    y: z
  zipkin:
    x:
    y:
  otlp:
    z:
    a:
```

This will enforce that only a single exporter is configured, but allow for the most flexibility for configuring the exporters themselves IMO

<sub>From [SyncLinear.com](https://synclinear.com) | [FLI-197](https://linear.app/flipt/issue/FLI-197/otel-exporter-config)</sub>

**Comment by GeorgeMac** [comment]
Do you mean `s/telemetry/tracing/` ? and I agree.
It appears we do:
```yaml
tracing:
  enabled: true
  jaeger:
    enabled: true
```

Instead of having a `type` or `exporter` as it is called there. Should we continue this pattern?
It implies you can have multiple exporters at once (keeping things consistent in this way).
Which might be not a bad thing. Also, I think we can achieve it with the `otel` libs. Just a little fiddly.
