### ISSUE TITLE
flipt import reports errors that flipt validate does not

### ISSUE THREAD

**Issue by ahobson** [flipt-io/flipt#2086]
### Describe the Bug

Running `flipt import` on a file where the rules reference a variant does not exist results in an error, but `flipt validate` does not report the error. In addition, running the same import a second time does not report any error.

### Version Info

```
Version: dev
Commit: a4d2662d417fb60c70d0cb63c78927253e38683f
Build Date: 2023-09-06T16:02:41Z
Go Version: go1.20.6
OS/Arch: darwin/arm64
```

### To Reproduce

```
# in one window, start flipt
./bin/flipt
# in another window 
./bin/flipt validate test.features.yaml
# no errors
./bin/flipt import --address http://localhost:8080 --create-namespace test.features.yaml
# this fails with
# Error: finding variant: not_a_variant; flag: bogus_rule_variant
./bin/flipt import --address http://localhost:8080 --create-namespace test.features.yaml
# This time it succeeds?
```

### Expected Behavior

Ideally, this would be an error `flipt validate` would be able to catch.

Ideally, the 2nd import would produce the same error.

#### Attach an Export

GitHub tells me it does not support attaching YAML files, so here's the file:

```yaml
namespace: test
flags:
  - key: bogus_rule_variant
    name: Bogus Rule Variant
    enabled: false
    variants:
      - key: bogus_one
        name: One
      - key: bogus_two
        name: Two
    rules:
      - segment: test-segment
        distributions:
          - variant: not_a_variant
            rollout: 100

segments:
  - key: test-segment
    name: Test Segement
    constraints:
      - type: STRING_COMPARISON_TYPE
        property: propertyOne
        operator: eq
        value: thingOne
    match_type: ALL_MATCH_TYPE
```
