### ISSUE TITLE
flipt export creates yaml file that flipt validate reports as invalid

### ISSUE THREAD

**Issue by ahobson** [flipt-io/flipt#2090]
### Describe the Bug

Exporting a rollout without a description creates a yaml file that `flipt validate` reports as invalid

### Version Info

```
Version: dev
Commit: a4d2662d417fb60c70d0cb63c78927253e38683f
Build Date: 2023-09-06T16:02:41Z
Go Version: go1.20.6
OS/Arch: darwin/arm64
```

This also happens with `v1.26.0`

### To Reproduce

1. Create a segment in the UI
2. Create a boolean flag in UI
3. Create rollout for flag using previously created segment
4. Run `flipt export --address http://localhost:8080`
5. Run `flipt validate` on the exported file. The error is:
```
Validation failed!

- Message  : flags.0.rollouts.0.description: incomplete value string
  File     : default.yaml
  Line     : 25
  Column   : 16
```

### Expected Behavior

The exported YAML should be valid.

#### Attach an Export

This is the exported YAML
```
version: "1.2"
namespace: default
flags:
- key: boolean-flag
  name: boolean flag
  type: BOOLEAN_FLAG_TYPE
  enabled: false
  rollouts:
  - segment:
      key: test-segment
      value: true
segments:
- key: test-segment
  name: test-segment
  match_type: ALL_MATCH_TYPE
```
