### ISSUE TITLE
Error Duing Starting up the docker

### ISSUE THREAD

**Issue by susanta96** [flipt-io/flipt#2123]
### Describe the Bug

I was trying to install via docker-compose, and faced lots of issues due lack of documentation, however getting it #now. this

### Version Info

Run `flip --version` and paste the output here: latest

### To Reproduce
Ubuntu server, just run the docker run or create docker-compose. 

### Expected Behavior

should start properly

### Additional Context

Please feel free to add any other context about the problem here.

Examples:

- OS: Ubuntu 20
- Config file used 
- Database used (SQLite, MySQL, Postgres, etc.) SQLite
- Screenshots
- Exported data from the database (see below)

#### Screenshots
flipt	{"error": "getting db driver for: sqlite3: unable to open database file: no such file or directory"}

**Comment by susanta96** [comment]
![image](https://ik.imagekit.io/4gk79wff3ko/plugin-upload/Screenshot_2023-09-16_at_3.11.48_PM_yXFlVoTYsG.JPG?tr=h-auto,f-auto)

**Comment by GeorgeMac** [comment]
Hey @susanta96,

Sorry about the frustrating experience getting flipt started. 
When I simply run via `docker run` I get the following:
```console
docker run -it --rm docker.io/flipt/flipt:v1.27.0

    _________       __
   / ____/ (_)___  / /_
  / /_  / / / __ \/ __/
 / __/ / / / /_/ / /_
/_/   /_/_/ .___/\__/
         /_/

Version: v1.27.0
Commit: 59440acb44a6cc965ac6146b7661100dd95d407e
Build Date: 2023-09-13T15:07:12Z
Go Version: go1.20.8
OS/Arch: linux/arm64

You are currently running the latest version of Flipt [v1.27.0]!

API: http://0.0.0.0:8080/api/v1
UI: http://0.0.0.0:8080
```

Could you perhaps provide the docker compose file you have?

**Comment by GeorgeMac** [comment]
My guess is the directory configured for your SQLite database file does not exist. But your config will help us know more.

**Comment by susanta96** [comment]
Sure, here is the docker-compose.yml.

```yml
 flipt:
    image: flipt/flipt:latest
    container_name: feature-flag
    restart: always
    extra_hosts:
      - "feature-flag:127.0.0.1"
    ports:
      - "8080:8080"
    volumes:
      - ./etc/flipt/config:/etc/flipt/config
      - ./var/opt/flipt:/var/opt/flipt
```
