### ISSUE TITLE
[Bug]: Cache issue when calling both the new variant evaluation api and the old one

### ISSUE THREAD

**Issue by rudineirk** [flipt-io/flipt#2236]
### Bug Description

We had 2 services calling Flipt to evaluate a flag in the same flow, with the same data, but one was calling the new `POST /evaluate/v1/variant` API and the other was still calling the deprecated `POST /api/v1/namespaces/{namespace}/evaluate` API. The first request that used the new API was sucessful, but the other one using the older API returned that the flag was disabled:

request:
```json
{
  "flagKey": "test-flag",
  "entityId": "c15a9c56-060b-4e17-a2cf-7216f9822f19",
  "context": {
    "account": "2f8ee5f6-42c9-4858-ab7c-35096ddddba1"
  },
  "requestId": "e54e57dc-3866-40bb-a16c-178bf64ca116"
}
```

response (200 OK):
```json
{
  "requestId": "e54e57dc-3866-40bb-a16c-178bf64ca116",
  "entityId": "",
  "requestContext": {
    "": "test-segment"
  },
  "match": false,
  "flagKey": "",
  "segmentKey": "",
  "timestamp": "2023-10-13T20:02:42.480371003Z",
  "value": "",
  "requestDurationMillis": 0.177695,
  "attachment": "",
  "reason": "UNKNOWN_EVALUATION_REASON",
  "namespaceKey": "",
  "segmentKeys": []
}
```

this only happens when calling using the older API after the newer one, seems to be related to cache, as this error was popping in the logs:
```
ERROR	unmarshalling from cache	{"server": "grpc", "error": "proto: cannot parse invalid wire-format data"}
```

looking in the code, it seems that Flipt is using the same cache key for both the older and the newer results:
https://github.com/flipt-io/flipt/blob/main/internal/server/middleware/grpc/middleware.go#L130
https://github.com/flipt-io/flipt/blob/main/internal/server/middleware/grpc/middleware.go#L231

### Version Info

```
Version: v1.28.1
Commit: 065e6ff7dc829c0b27bc0c188346b28bbf6e1b38
Build Date: 2023-10-04T19:29:33Z
Go Version: go1.20.8
OS/Arch: linux/amd64
```

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

- Create a variant flag that should return as enabled (see exported config bellow)
- Call the `POST /evaluate/v1/variant` API (should return as enabled, with the correct variant)
- Call the `POST /api/v1/namespaces/{namespace}/evaluate` with the same data (flag, entityId, requestId, context)
  - Here it should have returned the same result, but it returns as if the flag is disabled

### Expected Behavior

If a cache error happens, Flipt should skip the cache and make the method call without cache. Returning the flag as disabled is very dangerous (in our case resulted in data loss, we had to manually fix the cases where it returned the flag as disabled)

### Additional Context

Tested with PostgreSQL 14.5 and Redis 6.2.7

config:
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/flipt-io/flipt/main/config/flipt.schema.json

version: "1.0"
log:
  level: DEBUG

cors:
  enabled: false

cache:
  backend: redis
  enabled: true
  redis:
    host: redis
    port: 6379
    password: redis
    min_idle_conn: 10
    conn_max_idle_time: 60m
    net_timeout: 100ms
    pool_size: 10
  ttl: 30s

server:
  protocol: http
  host: 0.0.0.0
  http_port: 7500
  grpc_port: 7501
ui:
  enabled: true
authentication:
  required: false
  methods:
    token:
      enabled: true
      bootstrap:
        expiration: 8760h # 365 days
db:
  url: postgres://postgres:@postgres:5432/flipt?sslmode=disable
  conn_max_lifetime: 60m
  max_idle_conn: 5
  max_open_conn: 10
```

result from `flipt export`
```yaml
version: "1.2"
namespace: default
flags:
- key: test-flag
  name: test-flag
  type: VARIANT_FLAG_TYPE
  enabled: true
  variants:
  - key: enabled
  rules:
  - segment: test-segment
    distributions:
    - variant: enabled
      rollout: 100
segments:
- key: test-segment
  name: test-segment
  constraints:
  - type: STRING_COMPARISON_TYPE
    property: account
    operator: eq
    value: 2f8ee5f6-42c9-4858-ab7c-35096ddddba1
  match_type: ANY_MATCH_TYPE
```
