### ISSUE TITLE
[Bug]: Flags not from Default namespace does not appearing in git storage mode.

### ISSUE THREAD

**Issue by alexrios** [flipt-io/flipt#2284]
### Bug Description

I'm running Flipt in git storage mode successfully, using this configuration below to override the helm chart.

My client calling the Flipt server works fine, but when I visit the UI, I keep receiving the message in the image.

```yaml
flipt:
  config:
    log:
      level: DEBUG
    ui:
    authentication:
      required: false
    storage:
      type: git
      git:
        repository: <intentionally ommited>
        ref: "main"
        poll_interval: "5s"
        authentication:
          basic:
            username: <intentionally ommited>
            password: <intentionally ommited>
```

![image](https://github.com/flipt-io/flipt/assets/515382/c435d645-a73c-4f1e-b5e0-15c35d557650)

### Version Info

I'm using it in a K8s cluster through a helm chart, but **v1.29**.

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

1 - I'm my test; I have just one flag. This is my features.yml in the repository root:

```yaml
namespace: backend
flags:
  - key: test-flag
    name: Awesome New Feature
    enabled: true
```

2 - Visit the page http://localhost:8080/#/ (the default one)

3 - The error message appears at the bottom left of the page.

### Expected Behavior

Show the flags created on the git repository (storage) in the UI

### Additional Context

There are two current workarounds:

1 - Navigate explicitly to the namespace to see their flags: {host}/#/namespaces/backend/flags.

2 - Avoid using other namespace.
