### ISSUE TITLE
Add support for sending Audit Events to Slack (Audit Events)

### ISSUE THREAD

**Issue by yquansah** [flipt-io/flipt#2291]
We should add functionality for a Slack native sink.

Anyone interested in adding support for this is 💯 welcome to contribute!
We can provide guidance and pointers for this through our community outlets, [GitHub](https://github.com/flipt-io/flipt), or [Discord](https://flipt.io/discord).

As of the writing of this issue, we support a log file as an audit event sink, and generic webhooks. Slack is a popular medium of collaboration cross-organizationally, which suits the use case of it being an audit case fairly well.

## Details

1. [New `Sink` implementation](#implement-sink-interface)
2. [Add configuration for connection details](#provide-connection-details-for-the-slack-sink)
3. [Add conditional to enable sink](#add-conditional-to-enable-your-sink)
4. [Write tests](#write-tests)

### Implement `Sink` Interface

The `Sink` interface can be found [here](https://github.com/flipt-io/flipt/blob/main/internal/server/audit/audit.go#L182-L186). For this issue, we would need a custom implementation for Slack. In the same directory where the above file lives you can create a directory for `slack` and place the implementation of the `Sink` interface within a file in that directory.

The `Close` method will be called asynchronously, so make sure you account for that in your implementation in regards to your sink.

### Provide connection details for the Slack sink

Flipt will need to know how to connect to Slack community/channel, so we should provide the connection details as configuration to Flipt.

[Here](https://github.com/flipt-io/flipt/blob/main/internal/config/audit.go#L96-L99) is an example with how we achieve that with a regular log file.

### Add conditional to enable your sink

Just like the example [here], you want to create a similar condition for initiating the slack sink, and add the sink implementation to the `sinks` slice.

### Write tests

Write tests for your sink. The unit tests can be written in the same directory that your sink implementation lies.

**Comment by WDaan** [comment]
That would be neat! Currently doing this by leveraging our logging setup. This would allow us to skip that step.

**Comment by WDaan** [comment]
Haven't yet, I guess I could get it to work but does not seem worth to put in the effort to migrate it.
But thanks for linking me to it!

**Comment by kidanekal** [comment]
I ran into a similar issue, and the webbook and template engine saved the day; here is a sample template.

```
audit:
  sinks:
    webhook:
      enabled: true
      batch_size: 10
      batch_interval: 60s
      max_retries: 3
      backoff: 15s
      timeout: 5s
      templates:
        - url: "https://hooks.slack.com/services/XXXXXXXXX"
          headers:
            Content-Type: "application/json"
          body: |
            {
             "text": "```Audit Event: {{.Payload}} ```"
            }
```
