### ISSUE TITLE
[Bug]: Unable to perform Azure AD OIDC or GitHub site authorization, same response regardless (probably me).

### ISSUE THREAD

**Issue by richardj-bsquare** [flipt-io/flipt#2292]
### Bug Description

I've setup two authentication methods, an OIDC configuration via Azure AD and a GitHub Oauth...

When I try to auth via either method, it's clear that the auth works, however I always get the response in the callback of...

```
{"code":16,"message":"handling OIDC callback: unexpected state parameter","details":[]}
```

... Interestingly for both

My configuration is *almost* this (for obvious reasons I've changed the URL and creds):
```yaml
log:
  level: debug
  encoding: console

authentication:
  required: true
  session:
    domain: <redirect_host>
    secure: false
  methods:
    github:
      enabled: true
      email_matches:
        - ^.*@<email domain>$
      client_id: <id>
      client_secret: <secret>
      redirect_address: https://<redirect host>
      scopes:
        - user:email
    oidc:
      enabled: true
      email_matches:
        - ^.*@<email domain>$
      providers:
        azure: # insert your provider name
          issuer_url: https://login.microsoftonline.com/<tenant-id>/v2.0
          client_id: <azure-client-id>
          client_secret: <azure-client-secret>
          redirect_address: https://<redirect_host>
          scopes:
            - email
            - profile
```

Also, I checked the redirect from the authorize request and it does indeed contain a state parameter (so what is unexpected about it?), in this case the Azure AD provider...

```
https://<redirect_host>/auth/v1/method/oidc/azuread/callback?code=0.AS4AF_J4wLfDxka_dv8sRRz-mufSsNBHYyNCh9ujkV7KyXO5AFc.AgABAAIAAAAtyolDObpQQ5VtlI4uGjEPAgDs_wUA9P8HL4n_xnysH7d7u58WwxFcalYPc85l2p47HRHeW3lElBF59x1L3uuQhIijpyYsiDLfZHyVUJL_5lvntsSwDoPTXFCKCQA3cHitf9wBCHfG56PTqYgyQPwhyE1KwYlRRjWu2wnkm3ie3ICoUZvFNijnzqSZ-erXdmoTd1eIjd1Y5jqN6tAbELojABQnHoRkkHJVdU-YQQIj1nkyzU61qq3pvRIFhi5logKmUnlBVU1Ed2VuX91heobZQ8z2wBYPqTVJes5Xpmj4sMdfdf5ChXnP93yDUFBAle4-VnRkf6MtAF3aoayhuGYszBHT9ZD0RyaO6Sd-iFnft7ZprS-O6uBFTDUtpfijPBlvmgt9LUAItuGXebfDhvwbK4LKknLUwYBSKPgxiHlcc5kUcgzlffSxB45zFc0VK6wZnpKIf0VaK1U4e6KNgsDi2i9esOUYNxw1XYiuDfTFBeUEI7-OWu7D8ZG9xjo2_uD8-YVoAQxd7PsEV9cgOhTgDdsPWZLfgyK1rWKsdgrrVhTnNhnyQFtm5nAx4-50csiFIl8ekvdMttraQ-qipSyHPIZ-lEuJuezTZKTe6HFEDAQh79Y7T92e5Er-A6do1JZS1J49yW61Xm7WBXOJO60cVcA1lodsbl9n84N8Eq6gUqwATc-agYtXHDCXJuhXKBU_l82w7kSZ7uvoZSDl-6-LZcNFPpSq68XwdeCy1ZPivz8T9XLAiXv8XFfEnxN0AaTLnGjKHJWF1SCbCzN5AJiD4H5toM_e7PVEXU&state=eyJzZWN1cml0eV90b2tlbiI6InBOQ2loU0RYSlhvYWlSbUN1SDBnNE5UbkVvZV9kcTVMU2pickRvNW50d2dldGFuem1BQlhQOElPUVhRdnpPWFpTVlY3dXNXZWw0UVZYN0x4dDRTNWt3PT0iLCJvcmlnaW5hbF9zdGF0ZSI6IiJ9&session_state=f615238-2fb7-4424-a175-70498ed14c73
```
Again I've mangled the above a little, though the JWT token is decodable in the above.

### Version Info

```
    _________       __ 
   / ____/ (_)___  / /_
  / /_  / / / __ \/ __/
 / __/ / / / /_/ / /_  
/_/   /_/_/ .___/\__/  
         /_/           

Version: v1.29.0
Commit: 7aebc25baa3f0830f4dd846d29b39dffe96996a4
Build Date: 2023-10-23T17:36:20Z
Go Version: go1.21.3
OS/Arch: linux/amd64
```

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

Run the docker image with what appears to be a sane configuration...

### Expected Behavior

Auth should work.

### Additional Context

I realise that this is most likely a problem on my side, still, it would be useful to know what might be happening, and if possible, given you have verified this against Azure AD, some example configuration that you used to verify.

**Comment by GeorgeMac** [comment]
Hey @richardj-bsquare! Sorry this is causing you hassle.

Could you check the contents of your cookies for me.
Flipt will create a (optionally secure) cookie on the first leg of the login flow with the state parameter in it.
Then it ensures that the OIDC provider presents the same state security token in the state contents on the redirect.
The cookie is bound to the domain defined here:
```yaml
# ...
session:
  domain: <here>
# ...
```

Sounds like there is some mismatch going on there. Or perhaps we've got the cookie being bound on a slightly different domain? Just speculating.
