### ISSUE TITLE
[Bug]: Flip exported config does not round-trip

### ISSUE THREAD

**Issue by jalaziz** [flipt-io/flipt#2421]
### Bug Description

We recently built up a feature flag config in the Flipt UI with attachments. When we then tried to import it through the git integration, we saw very odd failures. Running `validate` also failed. 

The problems appears to be with attachments that are JSON lists. The Flipt UI happily accepts them and exports them, but they fail to import.

The exported file looked similar to:
```
version: "1.2"
namespace: default
flags:
  - key: supported-networks
    name: Supported Networks
    type: VARIANT_FLAG_TYPE
    enabled: true
    variants:
      - key: testnet-only
        name: Only Testnet Networks
        attachment:
          - POLYGON_TESTNET
          - ETHEREUM_TESTNET
      - key: all-networks
        name: All Networks
        attachment:
          - POLYGON_TESTNET
          - ETHEREUM_TESTNET
          - POLYGON_MAINNET
          - ETHEREUM_MAINNET
    rules:
      - segment: default
        distributions:
          - variant: testnet-only
            rollout: 100
```

And the quite confusing validation errors were:
```
- Message  : flags.0: 4 errors in empty disjunction:
  File     : features.yaml
  Line     : 0


- Message  : flags.0.type: conflicting values "BOOLEAN_FLAG_TYPE" and "VARIANT_FLAG_TYPE"
  File     : features.yaml
  Line     : 23


- Message  : flags.0.variants.0.attachment: 2 errors in empty disjunction:
  File     : features.yaml
  Line     : 0


- Message  : flags.0.variants.0.attachment: conflicting values ["POLYGON_TESTNET","ETHEREUM_TESTNET"] and {...} (mismatched types list and struct)
  File     : features.yaml
  Line     : 34


- Message  : flags.0.variants.0.attachment: conflicting values null and ["POLYGON_TESTNET","ETHEREUM_TESTNET"] (mismatched types null and list)
  File     : features.yaml
  Line     : 34
```

After some debugging, I realized that switching the attachments to maps fixed the issue.

### Version Info

v1.31.1

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

1. Build a flag configuration using the variant flag type
2. Add variants with JSON list attachments
3. Export the flag configuration
4. Run `flipt validate`
