### ISSUE TITLE
[FLI-738] Validate authentication configs at start

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#2532]
### Problem

Authentication configs are not currently fully validated at Flipt startup

For example this config:

```
authentication:
  methods:
    github:
      enabled: true
      scopes:
        - "user:email"
        - "read:org"
      allowed_organizations:
        - "flipt-io"
```

Allows Flipt to start up just fine, however, its not a valid config since `client_id`, `client_secret` and `redirect_address` are all required for the OAuth setup with GitHub: https://www.flipt.io/docs/configuration/authentication#github

### Ideal Solution

Now that we have per authentication method validation (added https://github.com/flipt-io/flipt/pull/2508/files#diff-9b81b9c76a5ad1bd617096d6af8c6bed965ca6c6b2505ce329d9d74151d0709cR257), we should now define the minimum set of required configuration for each authentication method and then add validation for each auth method we support so that Flipt will not start and warn the user of the invalid/missing fields.

### Search

- [X] I searched for other open and closed issues before opening this

<sub>[FLI-738](https://linear.app/flipt/issue/FLI-738/validate-authenticaton-configs-at-start)</sub>
