### ISSUE TITLE
[Bug]: Local evaluation does not have same behavior as remote

### ISSUE THREAD

**Issue by SamuelCabralCruz** [flipt-io/flipt#2859]
### Bug Description

Two flags with same configuration have different value using local evaluation.

### Version Info

1.38.0

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

Here is a configuration to reproduce the issue:

```yaml
# exported by Flipt (v1.38.0) on 2024-03-13T19:23:31Z
version: "1.2"
namespace: default
flags:
- key: 3410-redesign
  name: redesign
  type: BOOLEAN_FLAG_TYPE
  enabled: false
  rollouts:
  - segment:
      key: 0000-4a845c25fa825feac1813bf514e0ca76
      value: true
- key: 3410-redesign-dashboard
  name: redesign-dashboard
  type: BOOLEAN_FLAG_TYPE
  enabled: false
  rollouts:
  - segment:
      key: 0000-4a845c25fa825feac1813bf514e0ca76
      value: true
- key: 2697-internal-conversion
  name: 2697-internal-conversion
  type: BOOLEAN_FLAG_TYPE
  enabled: false
  rollouts:
  - segment:
      key: 0000-4a845c25fa825feac1813bf514e0ca76
      value: true
- key: 2709-event-v2
  name: 2709-event-v2
  type: BOOLEAN_FLAG_TYPE
  enabled: false
  rollouts:
  - segment:
      key: 0000-4a845c25fa825feac1813bf514e0ca76
      value: true
- key: 2709-sso-okta
  name: sso-okta
  type: BOOLEAN_FLAG_TYPE
  enabled: false
  rollouts:
  - segment:
      key: 0000-4a845c25fa825feac1813bf514e0ca76
      value: true
- key: 3049-orders-notes
  name: orders-notes
  type: BOOLEAN_FLAG_TYPE
  enabled: false
  rollouts:
  - segment:
      key: 0000-4a845c25fa825feac1813bf514e0ca76
      value: true
- key: 3049-search-v2
  name: search-v2
  type: BOOLEAN_FLAG_TYPE
  enabled: false
  rollouts:
  - segment:
      key: 0000-4a845c25fa825feac1813bf514e0ca76
      value: true
- key: 3049-orders-v2
  name: orders-v2
  type: BOOLEAN_FLAG_TYPE
  enabled: false
  rollouts:
  - segment:
      key: 0000-4a845c25fa825feac1813bf514e0ca76
      value: true
- key: 3409-orders-v3
  name: orders-v3
  type: BOOLEAN_FLAG_TYPE
  enabled: false
  rollouts:
  - segment:
      key: prd3049-de25e1db60b85fb8af93e73b60c390cf
      value: true
- key: 0000-v3
  name: 0000-v3
  type: BOOLEAN_FLAG_TYPE
  enabled: false
  rollouts:
  - segment:
      key: 0000-4a845c25fa825feac1813bf514e0ca76
      value: true
- key: 0000-context-v2
  name: context-v2
  type: BOOLEAN_FLAG_TYPE
  enabled: false
  rollouts:
  - segment:
      key: 0000-4a845c25fa825feac1813bf514e0ca76
      value: true
segments:
- key: 0000-4a845c25fa825feac1813bf514e0ca76
  name: or-always
  constraints:
  - type: BOOLEAN_COMPARISON_TYPE
    property: 844ac4e1-7b95-4689-a04b-8038acdb767e
    operator: notpresent
  match_type: ANY_MATCH_TYPE
- key: 3410-4a845c25fa825feac1813bf514e0ca76
  name: or-always
  constraints:
  - type: BOOLEAN_COMPARISON_TYPE
    property: 844ac4e1-7b95-4689-a04b-8038acdb767e
    operator: notpresent
  match_type: ANY_MATCH_TYPE
- key: prd3049-de25e1db60b85fb8af93e73b60c390cf
  name: or-organizationid-in-[1d1ac8ab6-6e8c-4531-aaa4-0610007e30eb, 93691b3a-55b0-44e8-9576-a5e4c43571cd,
    bc599a92-ecd6-4d9c-aef4-c0a39cc026f1, 3a1e1cde-c882-448a-9a48-38e424adcf6b]
  constraints:
  - type: STRING_COMPARISON_TYPE
    property: userId
    operator: isoneof
    value: '["1d1ac8ab6-6e8c-4531-aaa4-0610007e30eb","93691b3a-55b0-44e8-9576-a5e4c43571cd","bc599a92-ecd6-4d9c-aef4-c0a39cc026f1","3a1e1cde-c882-448a-9a48-38e424adcf6b"]'
  match_type: ANY_MATCH_TYPE
``` 

Using this configuration with local evaluation, the `3410-redesign` flag with an empty context return true, but `2709-sso-okta` which has the exact same configuration would return false.

### Expected Behavior

The same set up with remote evaluation gives the expected result, both flags are true.
