### ISSUE TITLE
[FLI-911] Remote config

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#2862]
### Problem

If you have multiple instances of Flipt (for HA, or any other reason), currently you have to copy the [config.yml file](https://www.flipt.io/docs/configuration/overview#configuration-file) between instances to have them configured the same.

### Ideal Solution

It could be nice if we allowed specifying config from a remote, such as Git or Cloud Bucket / Object Store.

We already have the code in place to read from these remote sources, so I don't think it would be a huge lift to support this.

This would allow users / operators to share config easily between instances.

### Search

- [X] I searched for other open and closed issues before opening this

<sub>[FLI-911](https://linear.app/flipt/issue/FLI-911/remote-config)</sub>

**Comment by piclemx** [comment]
Remote storage would be my first choice

**Comment by markphelps** [comment]
> Remote storage would be my first choice

So reading from S3/etc?

**Comment by piclemx** [comment]
Yes, S3 is what we are using for a lot of our stuff

**Comment by markphelps** [comment]
Now we just need to figure out how to bootstrap it. Like what makes sense for how to tell Flipt where to go (and how to authenticate) at startup to read the config file from the remote storage.

Maybe a paired down `config.yml` that points to the bucket / object store like we do for flag state: https://www.flipt.io/docs/configuration/storage#amazon-s3 ?

something like:

```
config:
  remote:
    type: object
    object:
      type: s3
      s3:
        region: us-east-1
        bucket: flipt_config
        # optional: bucket prefix for locating flag state files
        prefix: production
        # optional: for non-AWS hosted S3
        endpoint: http://localhost:9009
```

?

Then we would also need to decide if you could override any of the remote config properties by setting them in the local config too. Wdyt?
