### ISSUE TITLE
[Bug]: UI prevents the use of float for variant key

### ISSUE THREAD

**Issue by epahl-atlassian** [flipt-io/flipt#2882]
### Bug Description

<img width="556" alt="Screenshot 2024-03-21 at 12 52 00 PM" src="https://github.com/flipt-io/flipt/assets/61770799/0e36d5df-bba7-4bad-a682-68c23988ebe0">

### Version Info

1.38.2

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

1. Add variant flag
2. Attempt to add variant with a period e.g. `2.0`

### Expected Behavior

Allow the use of floats for a variant key

**Comment by markphelps** [comment]
Have confirmed that configuring variant keys with float string values works in .yaml:

```
namespace: default
flags:
  - key: example
    name: Example
    description: An example flag
    type: VARIANT_FLAG_TYPE
    variants:
      - key: "0.1"
        name: Variant 1
        description: The first variant
      - key: variant2
        name: Variant 2
        description: The second variant
```

UI after importing:

![CleanShot 2024-03-21 at 10 13 33@2x](https://github.com/flipt-io/flipt/assets/209477/00e17ed5-8243-4bc1-915e-944e35a1c245)
