### ISSUE TITLE
Support semantic versioning on Git declarative storage

### ISSUE THREAD

**Issue by thepabloaguilar** [flipt-io/flipt#2905]
### Problem

It's not a real problem as it seems to be workibng so far for everyone (or at least they don't have oppened an issue), would be great if people could specify a semantic version constraint like `1.1.*`, flipt will find the greater version based on that constraint!
It's great to let people define some strategies based on their preferences for managing the versions of the flags!

### Ideal Solution

Allow `ref` to accept semantic versioning constraints!
```yaml
storage:
  type: git
  git:
    repository: "https://github.com/predictab.le/config.git"
    ref: "1.1.*" # or v1.1.*
```

There's already a great lib for that, [Masterminds/semver](https://github.com/Masterminds/semver)

### Search

- [X] I searched for other open and closed issues before opening this

### Additional Context

Looking from outside it seems a great addition/change, WDYT?
