### ISSUE TITLE
JWT Auth: Support custom claim validation

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#2985]
Allow validating custom claims in JWT auth config

https://docs.flipt.io/configuration/authentication#claim-validation

We currently support validating `iss` and `aud`. We should probably add support for `sub` and secondly allow users to define custom claims that they want validated.

Perhaps under a `custom:` section?

```yaml
authentication:
  methods:
    jwt:
      enabled: true
      validate_claims:
        issuer: https://auth0.com/
        audiences: https://flipt.io/, https://flipt.com/ 
        subject: foo
        custom:
           x: y
           a: b
```

_Originally posted by @markphelps in https://github.com/flipt-io/flipt/issues/2945#issuecomment-2050687617_
