### ISSUE TITLE
Allow multiple metrics exporter (Prometheus, OpenTelemetry)

### ISSUE THREAD

**Issue by thepabloaguilar** [flipt-io/flipt#2997]
### Problem

Currently Flipt uses the OTel library to build up the application metrics but just provide the Prometheus exporter! Depending on the company guidelines it can be a "problem" if they use a APM/Metrics platform (New Relic, Datadog) to store and compute metrics and they want to be vendor-free by using only OTel stack

### Ideal Solution

The ideal solution would be to allow people chose what kind of exporter they want and keeping the current behavior for backward compatibility! Something like:

```yaml
metrics:
  prometheus:
    enabled: true # It should be the default value for backward compatibility
  otlp:
    enabled: true
    endpoint: "https://{your-collector-url}"
```

### Search

- [X] I searched for other open and closed issues before opening this

### Additional Context

Related #2978
