### ISSUE TITLE
[FLI-1041] [Bug]: Logout seems broken

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#3131]
### Bug Description

I've noticed this when using OIDC auth with Keycloak, this likely might be broken for other OIDC auth providers as well.

Whenever Im logged in using Keycloak OIDC, and I click `logout` in the UI, it doesn't actually log me out. Or at least if it does, it quickly re-logs me back in.

mp4 attached:

https://github.com/flipt-io/flipt/assets/209477/e40ee019-4eec-4702-bdf0-d37b3aba5a1e

### Version Info

Main

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

1. Setup Keycloak for OIDC
2. Configure Flipt, config below:

```yaml
authentication:
  required: true
  session:
    domain: localhost
  methods:
    oidc:
      enabled: true
      providers:
        keycloak:
          issuer_url: http://localhost:8080/realms/flipt
          redirect_address: http://localhost:8081
          client_id: flipt
          client_secret: <redacted>
```

3. Login via Keycloak
4. Try to logout
5. Notice behavior above

### Expected Behavior

Log out of Flipt UI, cookies and sessions are cleared. Get returned back to Flipt login screen

### Additional Context

This could be due to my change in #3082, as the `iss` issued from the Keycloak token is:

```
iss":"http://localhost:8080/realms/flipt"
```

<sub>[FLI-1041](https://linear.app/flipt/issue/FLI-1041/[bug]-logout-seems-broken)</sub>
