### ISSUE TITLE
[Bug]: Client SDK doesn't work correctly with EntityId segments

### ISSUE THREAD

**Issue by erka** [flipt-io/flipt#3261]
### Bug Description

https://discord.com/channels/960634591000014878/960697263150227510/1260187663005388840
> hey everyone, I'm having issues with the Browser based Client. If I try out my example via Console and add a specific EntityId, without context, which is used as Rollout Segment I do get back the proper result + `MATCH_EVALUATION_REASON` as message. With the browser client sdk on the other hand passing in the same EntityId without context always results in `DEFAULT_EVALUATION_REASON`
> any ideas what could cause that issue?
> interesting. As soon as I remove the entityId type constraint:
```json
{
    "id": "",
    "type": "UNKNOWN_CONSTRAINT_COMPARISON_TYPE",
    "property": "entityId",
    "operator": "eq",
    "value": "5055"
}
```
> and change it with the following numeric one
```json
{
    "id": "",
    "type": "NUMBER_CONSTRAINT_COMPARISON_TYPE",
    "property": "gridId",
    "operator": "eq",
    "value": "5055"
}
```

> and now pass in the following context:  `{"gridId": "5055"}`
it works

### Version Info

v1.45.0

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

- Import the configuration
```yaml
version: "1.2"
namespace: default
flags:
- key: flag
  name: flag
  type: BOOLEAN_FLAG_TYPE
  enabled: false
  rollouts:
  - segment:
      key: a
      value: true
segments:
- key: a
  name: a
  constraints:
  - type: ENTITY_ID_COMPARISON_TYPE
    property: entityId
    operator: eq
    value: a
  match_type: ALL_MATCH_TYPE
```

- evaluate flag with any client sdk
