### ISSUE TITLE
[Bug]: Can't run flipt import with default variant for a flag

### ISSUE THREAD

**Issue by erka** [flipt-io/flipt#3310]
### Bug Description

Import fails with 
```sh
Error: updating flag: variant "none" not found for flag "default/variant-flag"
exit status 1
```

### Version Info

main

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

- create `default.yml` file with content
```yaml
version: "1.3"
namespace: default
flags:
- key: variant-flag
  name: variant-flag
  type: VARIANT_FLAG_TYPE
  enabled: true
  variants:
  - key: azul
    attachment:
      apple: 134
      pear: false
  - default: true
    key: none
  rules:
  - segment: some
    distributions:
    - variant: azul
      rollout: 100
segments:
- key: some
  name: some
  constraints:
  - type: ENTITY_ID_COMPARISON_TYPE
    property: entityId
    operator: eq
    value: fruit
  match_type: ANY_MATCH_TYPE
```
- run `flipt import default.yml`
