### ISSUE TITLE
[Bug]: Got UNKNOWN_EVALUATION_REASON with default variant for a flag 

### ISSUE THREAD

**Issue by erka** [flipt-io/flipt#3311]
### Bug Description

I have this configuration
```yaml
version: "1.3"
namespace: default
flags:
- key: variant-flag
  name: variant-flag
  type: VARIANT_FLAG_TYPE
  enabled: true
  variants:
  - key: azul
    attachment:
      apple: 134
      pear: false
  - default: true
    key: none
  rules:
  - segment: some
    distributions:
    - variant: azul
      rollout: 100
segments:
- key: some
  name: some
  constraints:
  - type: ENTITY_ID_COMPARISON_TYPE
    property: entityId
    operator: eq
    value: fruit
  match_type: ANY_MATCH_TYPE
```
and I try to evaluate the flag 

```sh
flipt evaluate variant-flag --entity-id 082d910d-9250-4683-8d76-f0704f287cf2 --namespace default
```

I got the response 

```json
{
  "flag_key": "variant-flag",
  "match": false,
  "reason": "UNKNOWN_EVALUATION_REASON",
  "request_id": "6fe43684-1091-46d2-ab78-e2383ce4cf41",
  "request_duration_millis": 1.02,
  "timestamp": "2024-07-26T10:23:48.576877Z"
}
```

### Version Info

main

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

- import the file
- try evaluate the flag
