### ISSUE TITLE
Default sorting of flags ect to not be created time stamp

### ISSUE THREAD

**Issue by alucarddelta** [flipt-io/flipt#3413]
### Problem

Is it possible to change the default sorting of the flag table to be something other than the created timestamp.

When trying to view a bunch of flags, it is much easier to look for a key/name in alphabetical order.

### Ideal Solution

Have a config option under the UI section for default sort order, Allowing config values of:
- key
- name
- type
- created

eg
```yaml
 ui:
     table_sorting:
          flag: key
          segments: name
```

### Search

- [X] I searched for other open and closed issues before opening this
