### ISSUE TITLE
[Bug]: JSON import issue

### ISSUE THREAD

**Issue by kvnhmn** [flipt-io/flipt#3636]
### Bug Description

If you import an exported .json. You'll get an error, because of the first line in the json, which is a comment. 

### Version Info

v1.51.0

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

Export Flags as JSON then import it

**Comment by erka** [comment]
This is a minimal backup file which allows to repo the issue

```yaml
# exported by Flipt (v1.51.1) on 2024-11-21T11:39:38Z

version: "1.4"
namespace:
  key: default
  name: Default
  description: Default namespace
flags:
  - key: test
    name: test
    type: BOOLEAN_FLAG_TYPE
    enabled: false
    metadata:
      args:
        name: value
```
