### ISSUE TITLE
Understand the behaviour of empty `[]` segment of flag

### ISSUE THREAD

**Issue by BhautikChudasama** [flipt-io/flipt#3788]
### Description

- Recently, I created a flag without associating it with any segment. Why is it returning true every time I evaluate it? Someone help me to understand the behaviour.

**Comment by markphelps** [comment]
Hey @BhautikChudasama ! Would you be able to provide more info about:

1. what type of flag are you using? [boolean](https://docs.flipt.io/concepts#boolean-flags) or [variant](https://docs.flipt.io/concepts#variant-flags)
2. If `boolean` are you setting the default rollout value to `true`? (see image below)
3. can you give an example of what your evaluation request looks like?

![CleanShot 2025-01-06 at 08 57 34](https://github.com/user-attachments/assets/138a40c3-71ae-4d99-b32f-12b8db1563ee)

**Comment by BhautikChudasama** [comment]
Hey @markphelps, thanks for reply. I am using `Boolean` flag, Default rolloout value is false, and I am using `GitOps approach + OpenFeature sdk`.

```yaml
version: "1.2"
namespace: default
flags:
  - key: test2-cluster
    name: test2 Cluster
    type: BOOLEAN_FLAG_TYPE
    enabled: false
    rollouts:
    - segment:
        key: test2-providers
        value: true
segments:
  - key: test2-providers
    name: Staging 2 providers
    match_type: ANY_MATCH_TYPE
    constraints: []
```

### Screenshot
<img width="1439" alt="Screenshot 2025-01-06 at 7 50 17 PM" src="https://github.com/user-attachments/assets/06372a6d-21c8-4fdd-a2b6-9672672a130d" />
