### ISSUE TITLE
[audit] Issue with audit event when create/edit Segment and Rollout with Kafka sink

### ISSUE THREAD

**Issue by beanvuvanhau** [flipt-io/flipt#3825]
- **Action**: When `create/edit` Segment and Rollout, the audit event was written to the log file, but when changed sink to kafka

- **Expected**: audit event was send to Kafka

- **Actual**: it's **not** recorded 

Please help me with this issue 🙇 
**Config**: 
- Kafka sink:

```
audit:
  sinks:
    kafka:
      enabled: true
      topic: AuditLog
      encoding: avro
      bootstrap_servers:
      require_tls: true
      insecure_skip_tls: true
      authentication:
        username: ${KAFKA_USERNAME}
        password: ${KAFKA_PASSWORD}
      schema_registry:
        url: ${url}
```

- File sink:

```
audit:
  events: "*:*"
  enabled: true
  sinks:
    log:
      enabled: true
      file: /path-to/audit.log
      encoding: json
```
