### ISSUE TITLE
[Bug]: disabling UI and setting storage to read-only broken?

### ISSUE THREAD

**Issue by werwuifi** [flipt-io/flipt#4056]
### Bug Description

This is how I configured flipt in docker-compose:
```
  flipt:
    image: flipt/flipt:v1.57.0
    container_name: flipt
    restart: always
    entrypoint: ["/etc/flipt/entrypoint.sh"]
    volumes:
      - ./flipt/import:/var/opt/flipt/features
      - ./flipt/entrypoint.sh:/etc/flipt/entrypoint.sh
    ports:
      - "18080:8080"
    environment:
      - ENV_DEPLOY=${ENV_DEPLOY}
      - FLIPT_META_CHECK_FOR_UPDATES=true
      - FLIPT_META_TELEMETRY_ENABLED=false
      - FLIPT_LOG_LEVEL=debug
      - FLIPT_DB_URL=...
      - FLIPT_STORAGE_TYPE=database
      - FLIPT_STORAGE_READ_ONLY=true
      - FLIPT_UI_ENABLED=false
    networks:
      - platform
    depends_on:
      - postgresql
```
Setting
```  
      - FLIPT_STORAGE_READ_ONLY=true
      - FLIPT_UI_ENABLED=false
```
still allows me to access the UI and modify imported feature flags

### Version Info

v1.57.0

### Search

- [x] I searched for other open and closed issues before opening this

### Steps to Reproduce

use the docker-compose config from above

### Expected Behavior

UI should be disabled and feature flags should not be modifiable (according to the [docs](https://docs.flipt.io/configuration/storage#read-only-mode) a "read-only" label should appear)

### Additional Context

MacOS, Docker Engine 24.0.2, PostgreSQL database
