### ISSUE TITLE
[Bug]: V2: Logout in UI returns error

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#4093]
### Bug Description

Setup v2 with auth, in my case I used GitHub with redis storage:

```yaml
authentication:
  required: true
  session:
    domain: "localhost:8080"
    secure: false
    storage:
      type: "redis"
      redis:
        host: "localhost"
        port: 6379
        db: 0
      cleanup:
        grace_period: "30m"
  methods:
    github:
      enabled: true
    {github credentials in env vars}
```

### Version Info

v2 dev

### Search

- [x] I searched for other open and closed issues before opening this

### Steps to Reproduce

1. Login to UI
2. Logout
3. Get error
4. Refresh and you are logged out

![Image](https://github.com/user-attachments/assets/59b8c6e2-e644-420f-9587-29a3b18396e2)

### Additional Context
Logs:

```
2025-04-17T16:22:21-04:00       INFO    finished unary call with code NotFound  {"server": "grpc", "grpc.start_time": "2025-04-17T16:22:21-04:00", "system": "grpc", "span.kind": "server", "grpc.service": "flipt.auth.AuthenticationService", "grpc.method": "ExpireAuthenticationSelf", "peer.address": "0", "error": "rpc error: code = NotFound desc = getting authentication by id not found", "grpc.code": "NotFound", "grpc.time_ms": 3.848}
```
