### ISSUE TITLE
[Bug]: Percentage field does not accept zero values using oci

### ISSUE THREAD

**Issue by o-mago** [flipt-io/flipt#4291]
### Bug Description

Today is possible to set the Percentage to the value `0` using the UI
But when building the oci, if we set the percentage value to `0`, it will omit the field and generate the file without it:
```
{"description":"enabled for 0%","threshold":{"value":true}}
```

When flipt tries to read the config, it will throw an error
```
Error: flags.1.rollouts.0.threshold.percentage: incomplete value float | int (bf74696fa694712958a014394fd7b3f577b1c3578c3d426eca9db870cba78561.json 1)
flags.2.rollouts.0.threshold.percentage: incomplete value float | int (bf74696fa694712958a014394fd7b3f577b1c3578c3d426eca9db870cba78561.json 1)
```

### Which major version?

v1

### Version Info

v1.58.0

### Search

- [x] I searched for other open and closed issues before opening this

### Steps to Reproduce

Use the following config to build the bundle:
```
namespace: test

flags:
  - key: test
    name: test
    description: test
    type: BOOLEAN_FLAG_TYPE
    enabled: false
    rollouts:
      - threshold:
          percentage: 0
          value: true
```

Generate the file: `flipt bundle build local:test`

Open the bundle file, it will be as follow:
```
{"namespace":"test","flags":[{"key":"test","name":"test","type":"BOOLEAN_FLAG_TYPE","description":"test","enabled":false,"rollouts":[{"threshold":{"value":true}}]}]}
```

### Expected Behavior

The generated file should be as follow:
```
```
{"namespace":"test","flags":[{"key":"test","name":"test","type":"BOOLEAN_FLAG_TYPE","description":"test","enabled":false,"rollouts":[{"threshold":{"percentage":0,"value":true}}]}]}
```

### Additional Context

_No response_
