### ISSUE TITLE
How to add flag metadata when using declarative YAML?

### ISSUE THREAD

**Issue by asemarian** [flipt-io/flipt#4383]
Hey guys,

I've been wondering about how to add metadata to a flag when using a declarative file. So here's an example `feature.yml` file:
```
namespace:
  key: inventory
  name: Inventory
  description: Namespace for inventory-related feature flags

flags:
- key: test-flag
  name: test-flag
  type: BOOLEAN_FLAG_TYPE
  enabled: false
  description: Example description
  metadata:
    author: "Author's name"
    creationDate: "2025-06-26"
```

Is this correct YAML? `flipt validate` passes for this, yet I still don't see any metadata in the UI. Any help with this would be greatly appreciated 🙏
