### ISSUE TITLE
OAuth / API Token Support

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#779]
This issue is to track/help define adding OAuth (and likely API Token) support in both Flipt backend and Flipt UI. This will allow users to login to Flipt via existing third party services as well as provide basic auth for API requests.

My initial thoughts for this feature are:

1. Implement OAuth for GitHub/Gitlab only at first. As these seem to me to be the most likely third party services that users of Flipt would also depend on and already have accounts for. This also limits the amount of testing required to validate this feature by limiting the scope at first.
2. Design the feature in a way that additional providers could be added easily in the future (ex: Google, Azure, etc).
3. Make OAuth opt-in, as Flipt has not had auth up until this point, this would make the feature backwards compatible.
4. Since it seems that neither GitHub nor Gitlab support `client_credential` OAuth Grant type, we'd need a way for API requests (REST/GRPC) to also support auth without a user being present. We could add the ability for users to create API tokens for the machine to machine usecase (your app <-> Flipt). We could also implement scopes for these API tokens such as (management, evaluation) and TTL so that users  could limit what these tokens could do.

Further design docs/diagrams/potential DB schema will be added below.

**Comment by markphelps** [comment]
Im thinking of this from 'outside in' like how this would work from a user's perspective before diving into the the technical implementation.

Im currently basing the design of this feature off of how [grafana](https://github.com/grafana/grafana) has implemented authentication

Here's some docs from grafana:

- [API token auth](https://github.com/grafana/grafana/blob/23956557d8c6a119b7de5be5c42024e29634d002/docs/sources/http_api/auth.md)
- [GitHub  OAuth](https://github.com/grafana/grafana/blob/23956557d8c6a119b7de5be5c42024e29634d002/docs/sources/auth/github.md)
- [Gitlab OAuth](https://github.com/grafana/grafana/blob/23956557d8c6a119b7de5be5c42024e29634d002/docs/sources/auth/gitlab.md)

## Config

Here's what their [default config looks like for auth](https://github.com/grafana/grafana/blob/6c86f268814aac722f06c7ff0d8056e05d0a1d07/conf/defaults.ini#L428), we would use YAML instead, maybe adding TOML support for config would also make sense as an additional feature?

For Flipt I'm thinking the config could look like this:

```yaml
auth:
  anonymous:
    enabled: true # default since Flipt doesnt have auth now
  github:
    enabled: false # default
    allow_sign_up: true
    client_id: some_id
    client_secret: some_secret
    scopes: user:email,read:org
    auth_url: https://github.com/login/oauth/authorize
    token_url: https://github.com/login/oauth/access_token
    api_url: https://api.github.com/user
  gitlab:
      enabled: false # default
      allow_sign_up: true
      client_id: some_id
      client_secret: some_secret
      scopes: api
      auth_url:  https://gitlab.com/oauth/authorize
      token_url: https://gitlab.com/oauth/token
      api_url: https://gitlab.com/api/v4
```

If anonymous was `false` then one of the other auth providers would need to be enabled
